// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
};
